name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Vin-it-9 # Your GitHub username
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'

      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Generate snake animation'
